/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.alfredointerian.personal_financies.client;

import com.alfredointerian.personal_financies.auth.Session;
import com.alfredointerian.personal_financies.database.BankingAccount;
import com.alfredointerian.personal_financies.database.Movement;
import java.awt.Component;
import java.awt.Dimension;
import java.util.ArrayList;
import javax.swing.BoxLayout;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JScrollPane;

/**
 *
 * @author alfre
 */
public class ControlPanel extends javax.swing.JFrame {

    Session session = Session.getInstance();

    /**
     * Creates new form ControlPanel
     */
    public ControlPanel() {
        initComponents();

        this.setLocationRelativeTo(null);
        
        try {
            setBankingAccountList();
            setTotalBalance();    
            setLatestMovements();
        } catch (Exception e) {
            System.err.println(e);
        }
    }
    
    private void setLatestMovements () {
        LatestMovementsScroll.setHorizontalScrollBarPolicy(JScrollPane.HORIZONTAL_SCROLLBAR_AS_NEEDED); 
        LatestMovementsScroll.setVerticalScrollBarPolicy(JScrollPane.VERTICAL_SCROLLBAR_AS_NEEDED);
        
        LatestMovements.removeAll();
        
        for (Movement movement : session.getBankingAccountList().get(BankingAccountsList.getSelectedIndex()).fetchLatestMovements()) {
            LatestMovements.add(new MovementPanel(movement.getMovementConcept(), movement.getMovementDate(), movement.getMovementTime(), String.valueOf(movement.getMovementAmount())));
            
            System.out.println("Actualizando Lista de cuentas bancarias... " + movement.getMovementConcept());
        }
        
        int height = 1000;
        
        LatestMovements.setPreferredSize(new Dimension(400, height));

        LatestMovements.revalidate();
        LatestMovements.repaint();
        
        LatestMovementsScroll.revalidate();
        LatestMovementsScroll.repaint();
    }
    

    
    /**
     * Modifies CurrentBalance Label with the account balance
     */
    private void setTotalBalance () throws Exception {
        session.setTotalBalance(BankingAccountsList.getSelectedIndex());
        
        double total = session.getTotalBalance();
        CurrentBalanceLabel.setText("<html>Current Balance: " + ((total < 0) ? "<font color='red'>" + total + "</font>" : total) + "</html>");
    }

    private void setBankingAccountList() throws Exception {

        DefaultListModel<String> bankingAccountsList = new DefaultListModel<>();
        session.setBankingAccountList(BankingAccount.fetchBankingAccounts(session.getAccountId()));

        for (BankingAccount bankingAccount : session.getBankingAccountList()) {
            bankingAccountsList.addElement(bankingAccount.fetchBankingAccountName());
        }

        BankingAccountsList.setModel(bankingAccountsList);

        // Selects automatically the first element if it's possible
        if (BankingAccountsList.getModel().getSize() > 0) {
            BankingAccountsList.setSelectedIndex(0);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        WelcomeMsg = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        ListSlider = new javax.swing.JScrollPane();
        BankingAccountsList = new javax.swing.JList<>();
        LogOutBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        AddMovementBtn = new javax.swing.JButton();
        AddBankingAccountBtn = new javax.swing.JButton();
        BankingAccountSelectedOptionPanel = new javax.swing.JPanel();
        DeletaBankingAccountBtn = new javax.swing.JButton();
        CurrentBalanceLabel = new javax.swing.JLabel();
        LatestMovementsScroll = new javax.swing.JScrollPane();
        LatestMovements = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Banking Accounts");

        WelcomeMsg.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        WelcomeMsg.setText("Welcome, <username>");

        jLabel2.setText("Banking Accounts");

        BankingAccountsList.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                BankingAccountsListValueChanged(evt);
            }
        });
        ListSlider.setViewportView(BankingAccountsList);

        LogOutBtn.setText("Log Out");
        LogOutBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LogOutBtnMouseClicked(evt);
            }
        });

        jLabel1.setText("Lastest Movements");

        AddMovementBtn.setText("Add Movement");
        AddMovementBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AddMovementBtnMouseClicked(evt);
            }
        });

        AddBankingAccountBtn.setText("Add Banking Account");
        AddBankingAccountBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AddBankingAccountBtnMouseClicked(evt);
            }
        });

        DeletaBankingAccountBtn.setText("Delete Banking Account");
        DeletaBankingAccountBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DeletaBankingAccountBtnMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout BankingAccountSelectedOptionPanelLayout = new javax.swing.GroupLayout(BankingAccountSelectedOptionPanel);
        BankingAccountSelectedOptionPanel.setLayout(BankingAccountSelectedOptionPanelLayout);
        BankingAccountSelectedOptionPanelLayout.setHorizontalGroup(
            BankingAccountSelectedOptionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BankingAccountSelectedOptionPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(DeletaBankingAccountBtn)
                .addContainerGap(187, Short.MAX_VALUE))
        );
        BankingAccountSelectedOptionPanelLayout.setVerticalGroup(
            BankingAccountSelectedOptionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BankingAccountSelectedOptionPanelLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(DeletaBankingAccountBtn)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        CurrentBalanceLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        CurrentBalanceLabel.setText("Current Balance: <balance>");

        LatestMovementsScroll.setViewportView(LatestMovements);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(WelcomeMsg)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addGap(762, 762, 762)
                                    .addComponent(AddMovementBtn))
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel2)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(6, 6, 6)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(LogOutBtn)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                    .addComponent(AddBankingAccountBtn, javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(ListSlider, javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(BankingAccountSelectedOptionPanel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                    .addGap(79, 79, 79)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel1)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(6, 6, 6)
                                            .addComponent(LatestMovementsScroll, javax.swing.GroupLayout.PREFERRED_SIZE, 420, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGap(14, 14, 14)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(CurrentBalanceLabel)))
                .addContainerGap(32, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(WelcomeMsg)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CurrentBalanceLabel)
                .addGap(9, 9, 9)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(ListSlider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(AddBankingAccountBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(BankingAccountSelectedOptionPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(LogOutBtn)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(LatestMovementsScroll, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(53, 53, 53)
                        .addComponent(AddMovementBtn)
                        .addGap(205, 205, 205))))
        );

        WelcomeMsg.setText("Welcome, " + session.fetchAccountEmail());

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void LogOutBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LogOutBtnMouseClicked
        session.logout();

        Auth auth = new Auth();
        auth.setVisible(true);

        this.dispose();
    }//GEN-LAST:event_LogOutBtnMouseClicked

    private void AddMovementBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AddMovementBtnMouseClicked
        NewMovement newMovement = new NewMovement();
        newMovement.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_AddMovementBtnMouseClicked

    private void AddBankingAccountBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AddBankingAccountBtnMouseClicked
        AddBankingAccount addBankingAccount = new AddBankingAccount();
        addBankingAccount.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_AddBankingAccountBtnMouseClicked

    private void BankingAccountsListValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_BankingAccountsListValueChanged
        if (!evt.getValueIsAdjusting()) { // Select only when the user has selected
            System.out.println("Actualizando valores del panel de control..");
            
            session.setBankingAccountSelected(BankingAccountsList.getSelectedIndex());            
            
            try {
                setTotalBalance();
                setLatestMovements();
            } catch (Exception e) {
                System.err.println(e);
            }
            
        }
    }//GEN-LAST:event_BankingAccountsListValueChanged

    private void DeletaBankingAccountBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DeletaBankingAccountBtnMouseClicked

        if (JOptionPane.showConfirmDialog(this, "Are you sure about delete '" + session.getBankingAccountList().get(BankingAccountsList.getSelectedIndex()).fetchBankingAccountName() + "' account? This action isn't reversible", "Confirmartion", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
            session.getBankingAccountList().get(BankingAccountsList.getSelectedIndex()).deleteBankingAccountInDatabase();

            ControlPanel controlPanel = new ControlPanel();
            controlPanel.setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_DeletaBankingAccountBtnMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ControlPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ControlPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ControlPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ControlPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ControlPanel().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddBankingAccountBtn;
    private javax.swing.JButton AddMovementBtn;
    private javax.swing.JPanel BankingAccountSelectedOptionPanel;
    private javax.swing.JList<String> BankingAccountsList;
    private javax.swing.JLabel CurrentBalanceLabel;
    private javax.swing.JButton DeletaBankingAccountBtn;
    private javax.swing.JPanel LatestMovements;
    private javax.swing.JScrollPane LatestMovementsScroll;
    private javax.swing.JScrollPane ListSlider;
    private javax.swing.JButton LogOutBtn;
    private javax.swing.JLabel WelcomeMsg;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
