/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.alfredointerian.personal_financies.client;

import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Locale;

/**
 *
 * @author alfre
 */
public class MovementReceipt extends javax.swing.JFrame {

    /**
     * Creates new form MovementReceipt
     */
    public MovementReceipt(String concept, String description, String date, String time, String amount) {
        initComponents();

        try {
            SimpleDateFormat inputFormat = new SimpleDateFormat("yyyy-MM-dd");
            Date newDate = inputFormat.parse(date);
            
            SimpleDateFormat outputFormat = new SimpleDateFormat("EEEE, d 'de' MMMM 'del' yyyy", new Locale("es", "ES"));
            String longDate = outputFormat.format(newDate);
            DateLabel.setText(longDate);

        } catch (Exception e) {
            System.err.println("Date couldn't be formatted to long date. Using short date.");
            DateLabel.setText(date);
        }
        
        ConceptLabel.setText(concept);
        DescriptionLabel.setText(description);
        TimeLabel.setText(time);
        AmountLabel.setText("<html>$ " + ((Double.parseDouble(amount) < 0) ? "<font color='red'>" + amount + "</font>" : amount) + "</html>");
        
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ConceptLabel = new javax.swing.JLabel();
        DateLabel = new javax.swing.JLabel();
        TimeLabel = new javax.swing.JLabel();
        AmountLabel = new javax.swing.JLabel();
        CloseBtn = new javax.swing.JButton();
        DescriptionScroll = new javax.swing.JScrollPane();
        DescriptionLabel = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setAlwaysOnTop(true);

        ConceptLabel.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 24)); // NOI18N
        ConceptLabel.setText("<Concept>");

        DateLabel.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 14)); // NOI18N
        DateLabel.setText("<Date>");

        TimeLabel.setFont(new java.awt.Font("Microsoft YaHei UI Light", 0, 14)); // NOI18N
        TimeLabel.setText("<Time>");

        AmountLabel.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 14)); // NOI18N
        AmountLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        AmountLabel.setText("<Amount>");

        CloseBtn.setText("Cerrar");
        CloseBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CloseBtnMouseClicked(evt);
            }
        });

        DescriptionLabel.setEditable(false);
        DescriptionLabel.setColumns(20);
        DescriptionLabel.setRows(5);
        DescriptionLabel.setFocusable(false);
        DescriptionScroll.setViewportView(DescriptionLabel);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("Importe");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(ConceptLabel)
                        .addContainerGap(251, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(DescriptionScroll, javax.swing.GroupLayout.PREFERRED_SIZE, 361, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(AmountLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(DateLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(TimeLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(CloseBtn, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(DateLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TimeLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ConceptLabel)
                .addGap(18, 18, 18)
                .addComponent(DescriptionScroll, javax.swing.GroupLayout.DEFAULT_SIZE, 233, Short.MAX_VALUE)
                .addGap(56, 56, 56)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(AmountLabel)
                .addGap(40, 40, 40)
                .addComponent(CloseBtn)
                .addGap(14, 14, 14))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CloseBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CloseBtnMouseClicked
        this.dispose();
    }//GEN-LAST:event_CloseBtnMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AmountLabel;
    private javax.swing.JButton CloseBtn;
    private javax.swing.JLabel ConceptLabel;
    private javax.swing.JLabel DateLabel;
    private javax.swing.JTextArea DescriptionLabel;
    private javax.swing.JScrollPane DescriptionScroll;
    private javax.swing.JLabel TimeLabel;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
