/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.alfredointerian.personal_financies.client;

import com.alfredointerian.personal_financies.auth.Session;
import com.alfredointerian.personal_financies.database.Movement;
import java.time.LocalTime;
import java.time.format.DateTimeFormatter;
import javax.swing.JOptionPane;

/**
 *
 * @author alfre
 */
public class NewMovement extends javax.swing.JFrame {
    
    Session session = Session.getInstance();
    DateChooser dateChooser = new DateChooser();


    /**
     * Creates new form NewMovement
     */
    public NewMovement() {
        initComponents();
        this.setLocationRelativeTo(null);
        
        SelectedBankingAccountLabel.setText(session.fetchBankingAccountName());
        
        DateChooserPanel.add(dateChooser);
        DateChooserPanel.revalidate();
        DateChooserPanel.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        AmountField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        DescriptionScroll = new javax.swing.JScrollPane();
        DescriptionTextArea = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        ConceptField = new javax.swing.JTextField();
        AddMovementBtn = new javax.swing.JButton();
        ReturnBtn = new javax.swing.JButton();
        SelectedBankingAccountLabel = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        DateChooserPanel = new javax.swing.JPanel();
        DefaultTimeChkBox = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("New Movement");

        jLabel2.setText("Concept");

        jLabel3.setText("Description");

        DescriptionTextArea.setColumns(20);
        DescriptionTextArea.setRows(5);
        DescriptionScroll.setViewportView(DescriptionTextArea);

        jLabel4.setText("Amount");

        AddMovementBtn.setText("Add Movement");
        AddMovementBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AddMovementBtnMouseClicked(evt);
            }
        });

        ReturnBtn.setText("Cancel");
        ReturnBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ReturnBtnMouseClicked(evt);
            }
        });

        SelectedBankingAccountLabel.setText("<Selected Banking Account>");

        jLabel5.setText("Date");

        DefaultTimeChkBox.setSelected(true);
        DefaultTimeChkBox.setText("Use current time");
        DefaultTimeChkBox.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                DefaultTimeChkBoxItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(ReturnBtn)
                                    .addGap(89, 89, 89)
                                    .addComponent(AddMovementBtn))
                                .addComponent(AmountField, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(DescriptionScroll, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(ConceptField, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(DateChooserPanel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(DefaultTimeChkBox)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(SelectedBankingAccountLabel))
                            .addComponent(jLabel1))))
                .addContainerGap(29, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(SelectedBankingAccountLabel)
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ConceptField, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(DescriptionScroll, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(AmountField, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(DateChooserPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(DefaultTimeChkBox)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AddMovementBtn)
                    .addComponent(ReturnBtn))
                .addGap(21, 21, 21))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ReturnBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ReturnBtnMouseClicked
        ControlPanel controlPanel = new ControlPanel();
        controlPanel.setVisible(true);
        
        this.dispose();
    }//GEN-LAST:event_ReturnBtnMouseClicked

    private void AddMovementBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AddMovementBtnMouseClicked
        try {
        String movementConcept = ConceptField.getText();
        String movementDescription = DescriptionTextArea.getText();
        String movementAmountText = AmountField.getText();
                String movementTime = "HH:MM:SS";

        
        // Verify user input
        
        if (movementConcept.isBlank() || movementConcept.isEmpty()) {
            throw new Exception("Concept can't be empty");
        }
        
        if (movementDescription.isBlank() || movementDescription.isEmpty()) {
            throw new Exception("Description can't be empty");
        }
        
        if (movementAmountText.isBlank() || movementAmountText.isEmpty()) {
            throw new Exception("Amount can't be empty");
        }        

        // Convert amount into double
        
        Double movementAmount = Double.valueOf(movementAmountText);
        
        // Verify what time we should use
        
        if (!DefaultTimeChkBox.isSelected()) {
            // Usar la hora que emitió el usuario
        } else {
            // Usar la hora del equipo
            LocalTime localTime = LocalTime.now();
            DateTimeFormatter formatter = DateTimeFormatter.ofPattern("HH:mm:ss");
            movementTime = localTime.format(formatter);
        }

     
        Movement newMovement = new Movement(movementConcept, movementDescription, movementAmount, dateChooser.getDate(), movementTime,session.getBankingAccountSelected());
        
        if (JOptionPane.showConfirmDialog(this, "Is '" + movementConcept + "' movement information correct?", "Confirmation", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
            newMovement.addMovementToDatabase();
            
            ControlPanel controlPanel = new ControlPanel();
            controlPanel.setVisible(true);
            
            this.dispose();
        }
        
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "An error has been throwed. " + e);
            System.err.println(e);
        }
    }//GEN-LAST:event_AddMovementBtnMouseClicked

    private void DefaultTimeChkBoxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_DefaultTimeChkBoxItemStateChanged
        if (!DefaultTimeChkBox.isSelected()) {
            System.out.println("Abrir selector de hora");
        } else {
            System.out.println("Establecer hora del equipo");
        }
    }//GEN-LAST:event_DefaultTimeChkBoxItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewMovement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewMovement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewMovement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewMovement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewMovement().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddMovementBtn;
    private javax.swing.JTextField AmountField;
    private javax.swing.JTextField ConceptField;
    private javax.swing.JPanel DateChooserPanel;
    private javax.swing.JCheckBox DefaultTimeChkBox;
    private javax.swing.JScrollPane DescriptionScroll;
    private javax.swing.JTextArea DescriptionTextArea;
    private javax.swing.JButton ReturnBtn;
    private javax.swing.JLabel SelectedBankingAccountLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
